 const  dummyForumPosts = [
    {
        title: "How to get funding for my startup?",
        description: "I'm looking for funding options. Any advice?",
        category: "Funding",
        name: "John Doe",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "Best tech stack for SaaS startup?",
        description: "I'm debating between Next.js and React. Any thoughts?",
        category: "Technology",
        name: "Jane Smith",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "How to validate a startup idea?",
        description: "What steps should I take to validate my business idea?",
        category: "Business",
        name: "Anonymous",
        is_anonymous: true,
        created_at: new Date().toISOString(),
    },
    {
        title: "Marketing strategies for early-stage startups?",
        description: "What are the best growth hacking strategies?",
        category: "Marketing",
        name: "Startup Guy",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "Should I quit my job to start a startup?",
        description: "I'm debating whether I should go full-time on my startup.",
        category: "Career",
        name: "Anna Doe",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "Best co-founder matching platforms?",
        description: "Where can I find a good technical co-founder?",
        category: "Co-Founder",
        name: "Anonymous",
        is_anonymous: true,
        created_at: new Date().toISOString(),
    },
    {
        title: "How to pitch to investors?",
        description: "Any tips for creating a killer pitch deck?",
        category: "Funding",
        name: "Investor Seeker",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "Bootstrapping vs VC funding?",
        description: "Which is better for a startup with no revenue yet?",
        category: "Funding",
        name: "Bootstrapper",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "Legal requirements for startups?",
        description: "What legal steps should I take when starting a company?",
        category: "Legal",
        name: "Startup Lawyer",
        is_anonymous: false,
        created_at: new Date().toISOString(),
    },
    {
        title: "How to build an MVP fast?",
        description: "What’s the quickest way to get an MVP to market?",
        category: "Product Development",
        name: "Lean Startup",
        is_anonymous: false,   
        created_at: new Date().toISOString(),
    },
];


export default dummyForumPosts